### ISSUE TITLE
its not working in iOS 9.0 with Swift 2.0 in Xcode 7

### ISSUE THREAD

**Issue by alvinvarghese** [Lejdborg/NMSSH#156]
1. Error -> "_OBJC_CLASS_$_NMSSHSession", referenced from:

ld: warning: directory not found for option '-F/Volumes/Important/Dropbox/bitbucket/Dew Drive/Dew'
ld: warning: directory not found for option '-FDrive'
ld: warning: ignoring file /Volumes/Important/Dropbox/bitbucket/Dew Drive/Dew Drive/NMSSH.framework/NMSSH, missing required architecture x86_64 in file /Volumes/Important/Dropbox/bitbucket/Dew Drive/Dew Drive/NMSSH.framework/NMSSH (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_NMSSHSession", referenced from:
      type metadata accessor for ObjectiveC.NMSSHSession in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have these "arm64 armv7 armv7s" in my "valid architectures" in build settings. Please help me out to solve this.

**Comment by Lejdborg** [comment]
How are you installing NMSSH and which version are you trying to compile?

**Comment by alvinvarghese** [comment]
I just built the NMSSH iOS project in iOS 9.0, and dragged the framework into my project. After that i tried to run my project, then it shown this error.

**Comment by alvinvarghese** [comment]
Successfully integrated NMSSH, by using CocoaPods.
