### ISSUE TITLE
Archiving app with NMSSH Framework in Xcode 4.6 causes problems.

### ISSUE THREAD

**Issue by Carpetfizz** [Lejdborg/NMSSH#19]
Hello!
I'm using NMSSH in my iOS app, and it runs and works fine on the simulator and iOS devices. However, when I try to archive my app for distribution, I get the error message: 
Undefined symbols for architecture armv7s:

 _OBJC_CLASS_$_NMSSHSession", referenced from:
      objc-class-ref in UserPi.o
ld: symbol(s) not found for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)
